services:
  - type: web
    name: django-backend
    runtime: python
    plan: free
    rootDir: back
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn back.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: una-clave-secreta-segura
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "django-backend.onrender.com"

  - type: web
    name: next-frontend
    runtime: node
    plan: free
    rootDir: front
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://django-backend.onrender.com

  - type: web
    name: next-frontend
    runtime: node
    plan: free
    rootDir: front
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://django-backend.onrender.com
