# Generated by Django 5.0.7 on 2025-04-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpersonal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionpersonal.cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('LICENCIA', 'En licencia')], default='ACTIVO', max_length=10),
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_creacion',
        ),
    ]
